return {
    require("custom.plugins.harpoon"),
    require("custom.plugins.oil-vcs-status"),
    require("custom.plugins.autoclose"),
    require("custom.plugins.vim-fugitive"),
    require("custom.plugins.gitsigns"),
    require("custom.plugins.oil"),
    require("custom.plugins.nvim-ts-autotag"),
    require("custom.plugins.autosave"),
    require("custom.plugins.nvim-highlight-colors"),
    require("custom.plugins.python-venv-selector"),
    require("custom.plugins.lualine"),
    require("custom.plugins.github-theme"),
    require("custom.plugins.telescope"),
    require("custom.plugins.treesitter"),
}
