#!/bin/bash

#    ____            _            _    _ _                     
#   | __ )  __ _ ___| |__        / \  | (_) __ _ ___  ___  ___ 
#   |  _ \ / _` / __| '_ \      / _ \ | | |/ _` / __|/ _ \/ __|
#  _| |_) | (_| \__ \ | | |    / ___ \| | | (_| \__ \  __/\__ \
# (_)____/ \__,_|___/_| |_|___/_/   \_\_|_|\__,_|___/\___||___/
#                        |_____|                               

alias sl='ls'
alias ll='ls -Shlac --group-directories-first'
alias tree='tree --dirsfirst -a -C'

alias n='nvim .'
# alias ng='nvim . --listen 127.0.0.1:55432' # godot lsp

alias enc='nvim ~/.config/nvim/init.lua'
alias ebrc='nvim ~/.bashrc'
alias enix='sudo nvim /etc/nixos/configuration.nix && sudo nixos-rebuild switch --log-format bar-with-logs'

create_venv(){
    python -m venv venv || return;
    echo "Created venv successfully! Activating...";
    . venv/bin/activate
}

alias venv='. venv/bin/activate'

alias rm='rm -v '

alias cdg='cd ~/Documents/Git'
alias cdt='cd ~/Documents/Test'

alias fchat='cd ~/Documents/Git/fchat/ && nix-shell'

download_youtube_audio_mp3(){
    echo $1 >> ~/Music/.list
    yt-dlp -x --audio-format mp3 -o "~/Music/%(title)s.%(ext)s" $1
}

download_youtube_video_mp4(){
    yt-dlp --output-merge-format mp4 $1
}

alias scrcpy='scrcpy --turn-screen-off --render-driver=opengl'
alias screenkey='screenkey -s small -p fixed -g 10%x5%+88%+50%'
