#!/bin/bash

# 
#  /\/|  __                      __ _ _      
# |/\/  / /_  ___ __  _ __ ___  / _(_) | ___ 
#      / /\ \/ / '_ \| '__/ _ \| |_| | |/ _ \
#     / /_ >  <| |_) | | | (_) |  _| | |  __/
#    /_/(_)_/\_\ .__/|_|  \___/|_| |_|_|\___|
#              |_|                           
# 

pkexec xfpm-power-backlight-helper --set-brightness 2000
setxkbmap -option caps:swapescape
